default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8mb4
  pool: 20
  host: "0.0.0.0"
  username: "root"
  password: "toor"
  port: 43306

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

staging:
  <<: *default
  database: rails_staging

production:
  <<: *default
  database: rails_production
